### PR TITLE
docs(package.json): add repository

### PR DESCRIPTION
**Pull request by Haroenv**
very corporate and important information

### CODE REVIEW

**Comment by itsrachelfish** [comment]
Hey there, nice to meet you! Thank you for this contribution :sunglasses:

**Comment by Haroenv** [comment]
Nice to meet you Rachel! How are you

**Comment by itsrachelfish** [comment]
Doing good! Considering integrating floating.js into this project :wink:

**Comment by Haroenv** [comment]
❤️ It would work well for this. Let me know if it's missing something. 

By the way, you should check out https://bullg.it, it's kind of similar to the fishy website you have ☺️

**Pull request merged**
